# Generated by Django 5.0.1 on 2024-02-04 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_img', models.ImageField(upload_to='qr_codes/')),
                ('identifier', models.CharField(default='Iuv43WAKav', max_length=100, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='guest.guestdata')),
            ],
        ),
    ]
