# Generated by Django 4.2.10 on 2024-02-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/%d/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='guest.guestdata')),
            ],
        ),
    ]
