# Generated by Django 4.2.9 on 2024-01-30 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0002_event_members"),
        ("guest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.ImageField(upload_to="qr_codes/")),
                (
                    "identifier",
                    models.CharField(
                        default=django.utils.crypto.get_random_string,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qrcodes",
                        to="events.event",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qrcodes",
                        to="guest.guestdata",
                    ),
                ),
            ],
        ),
    ]
