# Generated by Django 4.2.9 on 2024-01-30 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_members"),
        ("guest", "0001_initial"),
        ("qrcode", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QRCode",
            new_name="Code",
        ),
    ]
