# Generated by Django 5.0.1 on 2024-02-04 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Kyiv', 'Kyiv'), ('Lviv', 'Lviv'), ('Zhytomyr', 'Zhytomyr')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default='00:00')),
                ('location', models.CharField(choices=[('Kyiv', 'Kyiv'), ('Lviv', 'Lviv'), ('Zhytomyr', 'Zhytomyr')], max_length=100)),
                ('max_seats', models.PositiveIntegerField(default=9999)),
                ('members', models.ManyToManyField(blank=True, related_name='events', to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.location')),
            ],
        ),
    ]
