# Generated by Django 4.2.9 on 2024-01-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="member.member"
            ),
        ),
    ]
