# Generated by Django 5.0.1 on 2024-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(default='Just Guest', max_length=150)),
                ('tg_login', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('company', models.TextField(blank=True)),
                ('position', models.TextField(blank=True)),
                ('events_attended', models.ManyToManyField(blank=True, to='events.event')),
            ],
        ),
    ]
